.eslintrc.json
client/routes.js
package-lock.json
package.json

added fullstack eslint
commented out play song

eslint stuff

---

client/components/BeetMaker2.js

qwerty keyboard basic functionality and relatively dry. Still need to look into if event listeners can be put in the button directly?

basic dry working custom scaleable keyboard

---

client/components/navbar.js

SiqBeets nav bar link now directs to '/'

fixed home link

---

client/components/BeetMaker2.js
client/components/DrumMachine.js

added some more beets

---

client/components/BeetMaker2.js

added test line for travis test

---

client/components/BeetMaker2.js

Temp branch for travis test

---

client/components/BeetMaker2.js
package-lock.json
package.json

Loop visuals

---

client/components/BeetMaker2.js

8n loops on click, will make 16n and 32n manual only

---

client/components/BeetMaker2.js

fixed wrapping keyboard on beetmaker2
fixed broken player
fixed broken loop maker sorry thad I broke your loop maker but i fixed it!! <3

fixed some small bugs from merges

---

client/components/BeetMaker2.js
client/components/DraggablePractice.js
client/components/DrumMachine.js

Refactored record loop

---

client/app.js
client/components/BeetMaker2.js
client/components/DrumMachine.js
client/components/Tracks.js
client/components/navbar.js
client/routes.js
public/index.html
public/style.css

BIG STUFF!
LOOP VISUALIZER IS PARTIALLY IMPLEMENTED
-still need to address state reloading the entire component and breaking everything
-need to add drag and drop functionality
-need to stlye note colors
SMALL STUFF
Some re-stlying and commenting out things that don't exist
some how fixed some bugs not sure how it happened with play button
fixed volume/speed slider thing
merged nikos drum machine and beetmakeralpha fixes

Loopstation

---

client/components/BeetMaker2.js
client/components/Tracks.js
client/components/navbar.js
client/components/toneSamples.js
client/routes.js
public/style.css

-fixed almost all of the bugs caused by state change except the sound stacking
-fixed a bunch of other small random bugs (0, volume/speed, simplekeyboard)
-commented out the loop visualization stuff for now as it is hella broken
-styled a few more things

fixed some minor bugs and cleaned some things up for beta testing

---

client/components/BeetMaker2.js

put almost everything on state and commented out loop station (doesn't have 4 measures worth of spots yet)

State changes

---

client/components/BeetMaker.js
client/components/BeetMaker2.js

zero button fixed

---

client/components/BeetMaker2.js
client/components/Tracks.js
client/store/sampler.js

Bugs:
-clear button needs 2 presses to clear
-visualizer is 1 step behind

Loop Fixes

---

client/components/BeetMaker2.js
client/components/DrumMachine.js
client/components/Looper.js
client/components/Tracks.js
public/style.css

Button colors

---

client/components/BeetMaker2.js
client/components/Modal.js

Finally fixed the audio context bug! I am so freaking excited about it!

Audio context bug fixed

---

client/components/BeetMaker2.js
public/style.css

button toggle working

---

.gitignore
client/components/BeetMaker2.js
client/components/SavedLoops.js
client/components/SignInTest.js
client/components/Tracks.js
client/routes.js
client/store/index.js
client/store/sampler.js
client/store/savedSongs.js
package-lock.json
package.json
public/index.html
server/api/index.js
server/api/songs.js
server/index.js

save and load ur poop but no google yet because travis is mad at firebaseConfig

Googleauthtest

---

client/components/BeetMaker.js
client/components/BeetMaker2.js
client/components/DrumMachine.js
client/components/Modal.js
client/components/SavedLoops.js
client/components/Tracks.js
client/components/toneSamples.js
public/style.css

Butt bug fixes hnnngg
